<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Hemodialysis extends Model
{
    use HasFactory;

    protected $table = 'hemodialysis';
    protected $primaryKey = 'ID';
    public $timestamps = false;
    protected $fillable = [
        'ID',
        'RECORDED_ON',
        'DATE',
        'CODE',
        'CUSTOMER_ID',
        'LOCATION_ID',
        'USER_ID',
        'NO_OF_TREATMENT',
        'MACHINE_NO',
        'PRE_WEIGHT',
        'PRE_BLOOD_PRESSURE',
        'PRE_HEART_RATE',
        'PRE_O2_SATURATION',
        'PRE_TEMPERATURE',
        'POST_WEIGHT',
        'POST_BLOOD_PRESSURE',
        'POST_HEART_RATE',
        'POST_O2_SATURATION',
        'POST_TEMPERATURE',
        'STATUS_ID',
        'STATUS_DATE',
        'TIME_START',
        'TIME_END',
        'PRE_BLOOD_PRESSURE2',
        'POST_BLOOD_PRESSURE2',
        'FILE_NAME',
        'FILE_PATH',
        'SE_DETAILS',
        'SO_DETAILS',
        'BFR',
        'DFR',
        'DURATION',
        'DIALYZER',
        'DIALSATE_N',
        'DIALSATE_K',
        'DIALSATE_C',
        'DETAILS_USE_NEXT',
        'ORDER_USE_NEXT',
        'IS_INCOMPLETE',
        'EMPLOYEE_ID',
        'SE_DETAILS_NEXT',
        'HEPARIN',
        'REUSE_NO',
        'REUSE_NEXT',
        'FLUSHING',
        'DOCTOR_ORDER',
        // - new
        'PRE_AMBULATORY',
        'PRE_AMBULATORY_W_ASSIT',
        'PRE_WHEEL_CHAIR',
        'PRE_CONSCIOUS',
        'PRE_COHERENT',
        'PRE_DISORIENTED',
        'PRE_DROWSY',

        'PRE_CLEAR',
        'PRE_CRACKLES',
        'PRE_RHONCHI',
        'PRE_WHEEZES',
        'PRE_RALES',

        'PRE_DISTENDED_JUGULAR_VIEW',
        'PRE_ASCITES',
        'PRE_EDEMA',
        'PRE_LOCATION',
        'PRE_LOCATION_NOTES',
        'PRE_DEPTH',
        'PRE_DEPTH_NOTES',

        'PRE_REGULAR',
        'PRE_IRREGULAR',

        'POST_AMBULATORY',
        'POST_AMBULATORY_W_ASSIT',
        'POST_WHEEL_CHAIR',
        'POST_CONSCIOUS',
        'POST_COHERENT',
        'POST_DISORIENTED',
        'POST_DROWSY',

        'POST_CLEAR',
        'POST_CRACKLES',
        'POST_RHONCHI',
        'POST_WHEEZES',
        'POST_RALES',

        'POST_DISTENDED_JUGULAR_VIEW',
        'POST_ASCITES',
        'POST_EDEMA',
        'POST_LOCATION',
        'POST_LOCATION_NOTES',
        'POST_DEPTH',
        'POST_DEPTH_NOTES',
        'POST_REGULAR',
        'POST_IRREGULAR',
        'SC_MACHINE_TEST',
        'SC_SECURED_CONNECTIONS',
        'SC_SALINE_LINE_DOUBLE_CLAMP',
        'SC_CONDUCTIVITY',
        'SC_DIALYSATE_TEMP',
        'SC_RESIDUAL_TEST_NEGATIVE',
        'DB_STANDARD_HCOA',
        'DB_ACID',
        'UF_GOAL',
        'AT_FISTULA',
        'AT_GRAFT',
        'AT_RIGHT',
        'AT_LEFT',
        'B_STRONG',
        'B_WEEK',
        'B_ABSENT',
        'T_STRONG',
        'T_WEAK',
        'T_ABSENT',
        'H_PRESENT',
        'H_ABSENT',
        'H_OTHER_NOTES',
        'CVC_SUBCATH',
        'CVC_JUGCATH',
        'CVC_FEMCATCH',
        'CVC_PERMACATH',
        'CVC_RIGHT',
        'CVC_LEFT',
        'CVC_GOOD_FLOW_A',
        'CVC_GOOD_FLOW_V',
        'CVC_W_RESISTANCE_A',
        'CVC_W_RESISTANCE_V',
        'CVC_CLOTTED_A',
        'CVC_CLOTTED_V',
        'DRY_WEIGHT',
        'RML',
        'HEPA_PROFILE',
        'CXR',
        'OTHER_INPUT'
    ];
}
