<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PhilHealth extends Model
{
    use HasFactory;
    protected $table = 'philhealth';
    protected $primaryKey = 'ID';
    public $timestamps = false;
    protected $fillable = [
        'ID',
        'RECORDED_ON',
        'CODE',
        'DATE',
        'LOCATION_ID',
        'CONTACT_ID',
        'DATE_ADMITTED',
        'TIME_ADMITTED',
        'DATE_DISCHARGED',
        'TIME_DISCHARGED',
        'FINAL_DIAGNOSIS',
        'OTHER_DIAGNOSIS',
        'FIRST_CASE_RATE',
        'SECOND_CASE_RATE',
        'STATUS_ID',
        'STATUS_DATETIME',
        'CHARGES_ROOM_N_BOARD',
        'CHARGES_DRUG_N_MEDICINE',
        'CHARGES_LAB_N_DIAGNOSTICS',
        'CHARGES_OPERATING_ROOM_FEE',
        'CHARGES_SUPPLIES',
        'CHARGES_OTHERS',
        'CHARGES_SUB_TOTAL',
        'OTHER_SPECIFY',
        'VAT_ROOM_N_BOARD',
        'VAT_DRUG_N_MEDICINE',
        'VAT_LAB_N_DIAGNOSTICS',
        'VAT_OPERATING_ROOM_FEE',
        'VAT_SUPPLIES',
        'VAT_OTHERS',
        'VAT_SUB_TOTAL',
        'SP_ROOM_N_BOARD',
        'SP_DRUG_N_MEDICINE',
        'SP_LAB_N_DIAGNOSTICS',
        'SP_OPERATING_ROOM_FEE',
        'SP_SUPPLIES',
        'SP_OTHERS',
        'SP_SUB_TOTAL',
        'GOV_ROOM_N_BOARD',
        'GOV_DRUG_N_MEDICINE',
        'GOV_LAB_N_DIAGNOSTICS',
        'GOV_OPERATING_ROOM_FEE',
        'GOV_SUPPLIES',
        'GOV_OTHERS',
        'GOV_SUB_TOTAL',
        'GOV_PCSO',
        'GOV_DSWD',
        'GOV_DOH',
        'GOV_HMO',
        'GOV_LINGAP',
        'P1_ROOM_N_BOARD',
        'P1_DRUG_N_MEDICINE',
        'P1_LAB_N_DIAGNOSTICS',
        'P1_OPERATING_ROOM_FEE',
        'P1_SUPPLIES',
        'P1_OTHERS',
        'P1_SUB_TOTAL',
        'P2_ROOM_N_BOARD',
        'P2_DRUG_N_MEDICINE',
        'P2_LAB_N_DIAGNOSTICS',
        'P2_OPERATING_ROOM_FEE',
        'P2_SUPPLIES',
        'P2_OTHERS',
        'P2_SUB_TOTAL',
        'OP_ROOM_N_BOARD',
        'OP_DRUG_N_MEDICINE',
        'OP_LAB_N_DIAGNOSTICS',
        'OP_OPERATING_ROOM_FEE',
        'OP_SUPPLIES',
        'OP_OTHERS',
        'OP_SUB_TOTAL',
        'PROFESSIONAL_FEE_SUB_TOTAL',
        'PROFESSIONAL_DISCOUNT_SUB_TOTAL',
        'CHARGE_TOTAL',
        'VAT_TOTAL',
        'SP_TOTAL',
        'GOV_TOTAL',
        'P1_TOTAL',
        'P2_TOTAL',
        'OP_TOTAL',
        'PREPARED_BY_ID',
        'DATE_SIGNED',
        'OTHER_NAME',
        'PAYMENT_AMOUNT',
        'AD_SUB_TOTAL',
        'AD_TOTAL',
        'IS_TEMP',
        'PF_RECEIVED_DATE',
        'AR_NO',
        'AR_DATE',
        'RR_NO',
        'CF4_DD_NOTES',
        'CF4_COMPLAINT',
        'CF4_HPI',
        'CF4_PPMH',
        'CF4_AD_NOTES',
        'PATIENT_PAYMENT_ID',
        'INVOICE_ID',
        'TIME_HIDE',
        'CLAIM_NO'
    ];

}
